# nginx標準構成用インストーラー
- hosts: all
  user: kunikiya
  sudo: yes
  tasks:
    # SELINUX無効用のパッケージ
    - name: install python-selinux
      yum: pkg=libselinux-python state=present

    # SELINUX無効
    #- name: disable selinux
    #  selinux: state=disabled

    # 基本
    - name: install vim
      yum: pkg=vim state=present
    #- name: install nkf
    #  yum: name=http://mirror.centos.org/centos/6/os/x86_64/Packages/nkf-2.0.8b-6.2.el6.x86_64.rpm state=latest
    - name: install man
      yum: pkg=man state=present

    - name: install Remi Repos
      yum: state=present name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

    - name: install Epel Repos
      yum: state=present name=http://ftp.iij.ad.jp/pub/linux/fedora/epel/7/x86_64/e/epel-release-7-5.noarch.rpm

    # webサーバ
#- include: part/mysql.yml
- include: part/php.yml
- include: part/nginx.yml
- include: part/mariadb.yml
- include: part/rubybundle.yml

