- hosts: all
  user: root
  tasks:
    - name: install mysql
      yum: name={{ item }} state=installed
      with_items:
        - mysql
        - mysql-server
        - mysql-devel
    - name: start mysql
      #action: service name=mysqld state=started
      service: name=mysqld state=started enabled=yes
